### ISSUE TITLE
각 서비스들을 swarm에서 kubernetes로 옮기기

### ISSUE THREAD

**Issue by pbzweihander** [upnl/work#53]
- [x] [swarm](https://github.com/upnl/swarm) 리포 이름을 kubernetes로 바꾸기
- [x] k3s에 aws-cloud-controller-manager 붙이는것 성공시키기
- 각 서비스 옮기기
  - [x] 홈페이지 @tirr-c
  - [x] 깃랩
  - [x] 포디비 @pbzweihander
  - [x] 헬릭스 @pbzweihander

**Comment by pbzweihander** [comment]
참고할만한 쿠버 파일

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homepage
  namespace: test
spec:
  rules:
    - host: gemini.upnl.org
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-deployment
              servicePort: 80
```
